/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthPathnameRouteImport } from './routes/auth/$pathname'
import { Route as AppProtectRouteRouteImport } from './routes/_app/_protect/route'
import { Route as AppArticleArticleIdRouteImport } from './routes/_app/article.$articleId'
import { Route as AppProtectEditorRouteImport } from './routes/_app/_protect/editor'
import { Route as AppProtectAccountSettingsRouteImport } from './routes/_app/_protect/account/settings'
import { Route as AppProtectAccountSecurityRouteImport } from './routes/_app/_protect/account/security'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProtectRouteRoute = AppProtectRouteRouteImport.update({
  id: '/_protect',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArticleArticleIdRoute = AppArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProtectEditorRoute = AppProtectEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppProtectRouteRoute,
} as any)
const AppProtectAccountSettingsRoute =
  AppProtectAccountSettingsRouteImport.update({
    id: '/account/settings',
    path: '/account/settings',
    getParentRoute: () => AppProtectRouteRoute,
  } as any)
const AppProtectAccountSecurityRoute =
  AppProtectAccountSecurityRouteImport.update({
    id: '/account/security',
    path: '/account/security',
    getParentRoute: () => AppProtectRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/editor': typeof AppProtectEditorRoute
  '/article/$articleId': typeof AppArticleArticleIdRoute
  '/account/security': typeof AppProtectAccountSecurityRoute
  '/account/settings': typeof AppProtectAccountSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/editor': typeof AppProtectEditorRoute
  '/article/$articleId': typeof AppArticleArticleIdRoute
  '/account/security': typeof AppProtectAccountSecurityRoute
  '/account/settings': typeof AppProtectAccountSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/_protect': typeof AppProtectRouteRouteWithChildren
  '/auth/$pathname': typeof AuthPathnameRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_protect/editor': typeof AppProtectEditorRoute
  '/_app/article/$articleId': typeof AppArticleArticleIdRoute
  '/_app/_protect/account/security': typeof AppProtectAccountSecurityRoute
  '/_app/_protect/account/settings': typeof AppProtectAccountSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/$pathname'
    | '/auth/verify-email'
    | '/editor'
    | '/article/$articleId'
    | '/account/security'
    | '/account/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/$pathname'
    | '/auth/verify-email'
    | '/editor'
    | '/article/$articleId'
    | '/account/security'
    | '/account/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_protect'
    | '/auth/$pathname'
    | '/auth/verify-email'
    | '/_app/'
    | '/_app/_protect/editor'
    | '/_app/article/$articleId'
    | '/_app/_protect/account/security'
    | '/_app/_protect/account/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthPathnameRoute: typeof AuthPathnameRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_protect': {
      id: '/_app/_protect'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppProtectRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/article/$articleId': {
      id: '/_app/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/article/$articleId'
      preLoaderRoute: typeof AppArticleArticleIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_protect/editor': {
      id: '/_app/_protect/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AppProtectEditorRouteImport
      parentRoute: typeof AppProtectRouteRoute
    }
    '/_app/_protect/account/settings': {
      id: '/_app/_protect/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AppProtectAccountSettingsRouteImport
      parentRoute: typeof AppProtectRouteRoute
    }
    '/_app/_protect/account/security': {
      id: '/_app/_protect/account/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AppProtectAccountSecurityRouteImport
      parentRoute: typeof AppProtectRouteRoute
    }
  }
}

interface AppProtectRouteRouteChildren {
  AppProtectEditorRoute: typeof AppProtectEditorRoute
  AppProtectAccountSecurityRoute: typeof AppProtectAccountSecurityRoute
  AppProtectAccountSettingsRoute: typeof AppProtectAccountSettingsRoute
}

const AppProtectRouteRouteChildren: AppProtectRouteRouteChildren = {
  AppProtectEditorRoute: AppProtectEditorRoute,
  AppProtectAccountSecurityRoute: AppProtectAccountSecurityRoute,
  AppProtectAccountSettingsRoute: AppProtectAccountSettingsRoute,
}

const AppProtectRouteRouteWithChildren = AppProtectRouteRoute._addFileChildren(
  AppProtectRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppProtectRouteRoute: typeof AppProtectRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppArticleArticleIdRoute: typeof AppArticleArticleIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProtectRouteRoute: AppProtectRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppArticleArticleIdRoute: AppArticleArticleIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthPathnameRoute: AuthPathnameRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
